### ISSUE TITLE
transform() kicks out input types used by directives

### ISSUE THREAD

**Issue by henkesn** [AEB-labs/graphql-transformer#1]
```graphql
input SomeInputType {
  name: String
}

directive @someDirective(names: [SomeInputType!]!) on TYPE
```

After running `transform()`, the input type `SomeInputType` is missing, although used by `@someDirective`.

I think the error is that remove-unused-types.ts only searches for reachable interfaces starting from the root types. There should be a search for reachable interfaces for directive definition args, too.

**Comment by Yogu** [comment]
I think this is a bug in `graphql-js`, so I opened PR graphql/graphql-js#1189 with a failing test.
